USE [CustInfo]
GO
SET IDENTITY_INSERT [dbo].[PermissionRecord] ON 

INSERT [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (1, N'Access admin area', N'AccessAdminPanel', N'Standard')
INSERT [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (2, N'Admin area. Manage Customers', N'ManageCustomers', N'Customers')
SET IDENTITY_INSERT [dbo].[PermissionRecord] OFF
INSERT [dbo].[PermissionRecord_Role_Mapping] ([PermissionRecord_Id], [CustomerRole_Id]) VALUES (1, 1)
INSERT [dbo].[PermissionRecord_Role_Mapping] ([PermissionRecord_Id], [CustomerRole_Id]) VALUES (1, 3)
INSERT [dbo].[PermissionRecord_Role_Mapping] ([PermissionRecord_Id], [CustomerRole_Id]) VALUES (2, 1)
INSERT [dbo].[PermissionRecord_Role_Mapping] ([PermissionRecord_Id], [CustomerRole_Id]) VALUES (2, 3)
SET IDENTITY_INSERT [dbo].[LocaleStringResource] ON 

INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (3, 1, N'Account.Login.NewCustomer', N'New Customer')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (4, 1, N'Account.Login.NewCustomerText', N'By creating an account on our website you will be able to shop faster, be up to date on an orders status, and keep track of the orders you have previously made.')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (5, 1, N'Account.Register', N'Register')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (6, 1, N'account.login.returningcustomer', N'Returning Customer')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (7, 1, N'Account.Login.Fields.Email', N'Email')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (8, 1, N'Account.Login.Fields.Password', N'Password')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (9, 1, N'Account.Login.Fields.RememberMe', N'RememberMe')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (10, 1, N'Account.Login.LoginButton', N'Login Button')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (11, 1, N'account.login.welcome', N'Welcome')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (12, 1, N'account.yourpersonaldetails', N'Your Personal Details')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (13, 1, N'Account.Fields.FirstName', N'First Name')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (14, 1, N'Account.Fields.LastName', N'Last Name')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (15, 1, N'Account.Fields.Email', N'Email')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (16, 1, N'Account.Fields.Password', N'Password')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (17, 1, N'Account.Fields.ConfirmPassword', N'Confirm Password')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (18, 1, N'Account.Register.Button', N'Register')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (19, 1, N'Account.YourPassword', N'Your Password')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (20, 1, N'Admin.Customers.Customers.Fields.Email', N'Email')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (21, 1, N'Admin.Customers.Customers.Fields.Username', N'Name')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (22, 1, N'Admin.Customers.Customers.Fields.CustomerRoles', N'Role')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (23, 1, N'Admin.Customers.Customers.Fields.Active', N'Active')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (24, 1, N'Admin.Customers.Customers.Fields.CreatedOn', N'CreatedOn')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (25, 1, N'Admin.Customers.Customers.Fields.LastActivityDate', N'LastActivityDate')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (26, 1, N'Admin.Common.Edit', N'Edit')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (27, 1, N'Admin.Customers.Customers.List.CustomerRoles', N'CustomerRoles')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (28, 1, N'Admin.Customers.Customers', N'Customers')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (29, 1, N'Admin.Common.AddNew', N'AddNew')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (30, 1, N'Admin.Common.ExportToXml.All', N'ExportToXmlAll')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (31, 1, N'Admin.Common.ExportToXml.Selected', N'ExportToXmlSelected')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (32, 1, N'Admin.Common.ExportToExcel.All', N'ExportToExcelAll')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (33, 1, N'Admin.Common.ExportToExcel.Selected', N'ExportToExcelSelected')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (34, 1, N'Admin.Customers.Customers.List.SearchDateOfBirth.Month', N'Month')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (35, 1, N'Admin.Customers.Customers.List.SearchDateOfBirth.Day', N'Day')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (36, 1, N'Admin.Common.Search', N'Search')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (37, 1, N'Admin.Customers.Customers.List.SearchEmail', N'Email')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (38, 1, N'Admin.Customers.Customers.List.SearchEmail.Hint', N'Search by a specific email')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (39, 1, N'Admin.Customers.Customers.List.SearchFirstName', N'First Name')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (40, 1, N'Admin.Customers.Customers.List.SearchFirstName.Hint', N'Search by a first name.')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (41, 1, N'Admin.Customers.Customers.List.SearchLastName', N'LAast Name')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (42, 1, N'Admin.Customers.Customers.List.SearchLastName.Hint', N'Search by a last name.')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (45, 1, N'Admin.Customers.Customers.Info', N'Customer Info')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (46, 1, N'Admin.Customers.Customers.CustomerRoles', N'Customer Roles')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (47, 1, N'Admin.Customers.Customers.AddNew', N'Add a new customer')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (48, 1, N'Admin.Customers.Customers.BackToList', N'back to customer list')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (49, 1, N'Admin.Common.Save', N'Save')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (50, 1, N'Admin.Common.SaveContinue', N'SaveContinue')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (51, 1, N'Admin.Customers.Customers.Fields.Password', N'Password')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (52, 1, N'Admin.Customers.Customers.Fields.FirstName', N'FirstName')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (53, 1, N'Admin.Customers.Customers.Fields.LastName', N'LastName')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (54, 1, N'Admin.Customers.Customers.Fields.Password.Change', N'Change Password')
INSERT [dbo].[LocaleStringResource] ([Id], [LanguageId], [ResourceName], [ResourceValue]) VALUES (55, 1, N'admin.common.delete', N'Delete')
SET IDENTITY_INSERT [dbo].[LocaleStringResource] OFF
SET IDENTITY_INSERT [dbo].[Setting] ON 

INSERT [dbo].[Setting] ([Id], [Name], [Value], [StoreId]) VALUES (1, N'customersettings.defaultpasswordformat', N'Hashed', 0)
INSERT [dbo].[Setting] ([Id], [Name], [Value], [StoreId]) VALUES (2, N'customersettings.userregistrationtype', N'Standard', 0)
INSERT [dbo].[Setting] ([Id], [Name], [Value], [StoreId]) VALUES (3, N'localizationsettings.loadalllocalerecordsonstartup', N'True', 0)
INSERT [dbo].[Setting] ([Id], [Name], [Value], [StoreId]) VALUES (4, N'adminareasettings.defaultgridpagesize', N'15', 0)
INSERT [dbo].[Setting] ([Id], [Name], [Value], [StoreId]) VALUES (5, N'adminareasettings.gridpagesizes', N'10, 15, 20, 50, 100', 0)
INSERT [dbo].[Setting] ([Id], [Name], [Value], [StoreId]) VALUES (7, N'adminareasettings.richeditoradditionalsettings', N' ', 0)
INSERT [dbo].[Setting] ([Id], [Name], [Value], [StoreId]) VALUES (8, N'adminareasettings.richeditorallowjavascript', N'False', 0)
SET IDENTITY_INSERT [dbo].[Setting] OFF
